#!/bin/sh

DISTRO=`cat /etc/*-release | grep ^ID= | grep -Po '".*?"' | tr -d '"'`

cat <<EOF
This is a S2I PHP ${DISTRO} base image:
To use it, install S2I: https://github.com/openshift/source-to-image
Sample invocation:
s2i build git@yourepository Digi59404/openshift-php-bare output-image-name
You can then run the resulting image via:
docker run -p 8000:8000 output-image-name
EOF